# Utilizamos la imagen base de nginx
FROM nginx:latest

# Copiamos el archivo index.html modificado al contenedor
COPY index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80 para que Nginx pueda servir la página web
EXPOSE 80

